$.jStorage.set('language', {
	en : {
		restart : 'restart',
		generateInverse : 'generate inverse relations',
		autoExpand : 'auto-expand mode',
		autoSameAs : 'generate inverse sameAs relations',
		autoCollectImages : 'collect images during browsing',
		autoDrawMap : 'geolocalize resources',
		noName : 'no title provided',
		addUri : 'insert an URI',
		findResource : 'find resources',
		choose : 'choose...',
		resourceMissing : 'resource not found',
		resourceMissingDoc : 'literal values not found or the resource is missing or not available in the endpoint',
		options : 'OPTIONS',
		endpointNotConfigured : 'no endpoint configured for the resource',
		endpointNotConfiguredSoInternal : 'no endpoint configured for the resource, generating temporary graph',
		impostaUnaURI : 'insert an uri, make a query or choose one of the examples provided',
		example : 'example',
		noIe : 'Sorry but Internet Explorer is not totally supported.',
		enpointNotAvailable : 'error: endpoint not available',
		enpointNotAvailableOrSLow : 'error: endpoint not available or the request timed out',
		imagesNotFound : 'no images for the opened resources',
		mapNotFound : 'no maps for the opened resources',
		propsNotFound : 'nothing found',
		propsFound : 'properties found',
		showResource : 'highlight the resource',
		zoomIn : 'zoom in',
		showConsole : 'show console (experimental)',
		executeThisQuery : 'execute the SPARQL query in a new window',
		moreInfoOnThis : 'more info on this resource',
		simpleSearch : 'simple search',
		simpleSearchDescription : 'DBpedia.org and Freebase allow  their resources to be queried through keywords.<br/><br/>You will be able to find the URIs of the resources  you want to explore by choosing a dataset and typing at least three letters of a keyword for it.',
		insertUri : 'insert URI',
		insertUriDescription : 'LodLive is able to analyse and "show"  RDF resources even when they are  not supported by a SPARQL access EndPoint.<br/><br/>By entering any URI to an RDF resource,  you will be able to explore contents and relationships.',
		insertData : 'browse your data',
		centerClose : 'focus on the resource',
		openOnline : 'access the online resource',
		openRelated : 'expand related resources',
		removeResource : 'remove this box',
		noImage:'image not available',
		connectedResources:'connected resources'
	},
});

$.jStorage.set('selectedLanguage', 'en');
